### ISSUE TITLE
Library is blocking UI updates in Ionic 2

### ISSUE THREAD

**Issue by marcelgoya** [smooch/smooch-js#440] opened 2016-11-16 23:40 UTC
Hi guys,

I'm currently using the SDK with the latest Ionic 2 beta and it seems to be blocking UI updates once the library is loaded. It happens for example when I open a modal dialog and it's supposed to update the main dialog once the modal is closed. This does not happen when the SDK is loaded. Also generally UI updates only appear when I click somewhere in the dialog, which normally doesn't happen. It would be great if you could have a look at this.

Many thanks,
Marcel

**Comment by lemieux** [comment] 2016-11-16 23:48
Hey @marcelgoya,

could this be the same problem/solution https://github.com/smooch/smooch-js/issues/416#issuecomment-260846648 ?

**Comment by marcelgoya** [comment] 2016-11-17 00:04
Hey @lemieux 

thanks for the quick reply. I've followed the example written in the blog post but the problem does not go away. I'm loading the SDK last in my index.html and I'm using the declare var method. Btw, I'm only experiencing the problem in Google Chrome for Mac/Win, not on mobile.

**Comment by lemieux** [comment] 2016-11-17 00:08
Can you provide a sample project to replicate this? Otherwise, it's a bit difficult for us to replicate the problem.

**Comment by marcelgoya** [comment] 2016-11-17 00:09
Sure, I'll create one tomorrow morning.

**Comment by lemieux** [comment] 2016-11-17 00:12
Thanks!

**Comment by marcelgoya** [comment] 2016-11-17 00:12
No prob!

**Comment by thielCole** [comment] 2016-11-25 15:18
@marcelgoya I haven't actually tried to use smooch and ionic deploy yet so I would be interested to hear what you have found. My best guess is that if there is a conflict, it is arising because of the issues that we found earlier where smooch and zone.js promise implementations conflict.

**Comment by marcelgoya** [comment] 2016-11-25 15:20
@thielCole I'm going to create a demo app today, so I can isolate the issue. I'll upload within the next couple of hours with my findings

**Comment by marcelgoya** [comment] 2016-11-25 16:52
@lemieux @thielCole 
Hi guys, I've just created a demo based on the cutepuppypics example. Basically what happens is that once you load the Smooch SDK, UI updates in general become non-responsive. You can see it in the demo when you click on the language select button, select a language and the text in the input field doesn't change. Everything works fine until I uncomment the Smooch.Init function in app.component.ts. Hope this helps 😎  

PS: I didn't add an API key in the example and you'd have to run npm install before you're running it.  
[cutePuppyPics.zip](https://github.com/smooch/smooch-js/files/613646/cutePuppyPics.zip)

**Comment by marcelgoya** [comment] 2016-12-01 14:15
@lemieux Any updates? I'm asking because I'm going to launch a new product in the next 2-3 weeks and I need this bug fixed or at least a workaround. The problem is that this bug makes it impossible for me to use your web SDK.

**Comment by jpjoyal** [comment] 2016-12-01 15:33
@marcelgoya We were able to reproduce the problem with your sample. Removing the init call was not sufficient to restore UI updates but removing the lib worked.

This seems to point toward a clash in the polyfills we embed in the lib with the one you are adding yourself or the ones that ionic is adding. 

A potential workaround would be to bake your own build by selecting which polyfill the smooch build should embed.

We currently don't support or test specifically for Ionic. Most of our mobile investment goes toward our high quality native [iOS](https://github.com/smooch/smooch-ios) and [Android](https://github.com/smooch/smooch-android) SDKs and we strongly recommend those for the best user and developer experience for mobile apps.

That said, if you find a workaround or a way to patch this specific behaviour, PRs or instructions on this issue are very welcome since Web messenger is fully open source.

**Comment by marcelgoya** [comment] 2016-12-01 15:54
@jpjoyal I would assume that since Ionic 2 is using Angular 2 as their foundation this problem would be related to Angular 2 in general and not only Ionic 2. Angular 2 as you surely know yourself is the biggest JS MVC framework on the market, next to React from FB. So I'd assume that you as a company should support at least the major frameworks. 

I selected your platform for my customer support purely because you have SDk's available on all 3 platforms, and now you're telling me as a paying customer that you don't maintain your Web SDK and you leave it up to your customers to fix bugs themselfs because you open sourced it?! Please enlighten me if I got this totally wrong.

**Comment by marcelgoya** [comment] 2016-12-01 16:01
And btw, we're talking about 99 $ per month, which to a self funded startup is a lot of money compared to ZenDesk and co.

**Comment by jpjoyal** [comment] 2016-12-01 18:08
We are committed to maintain Web messenger. Compatibility with frameworks and combination of them is a known challenge in the javascript community and although we do our best in that regard we have to measure and justify the effort we deploy in that regard. 

I’ve been unable to reproduce this UI update problem using a [plain angular 2](https://github.com/tastejs/todomvc/tree/master/examples/angular2) project. 

This seems to point to something specific to ionic 2 beta.

**Comment by marcelgoya** [comment] 2016-12-01 18:16
I bet you are! Especially when this SDK is part of a paid service. Fair enough, so that means you're not planning to make this SDK compatible with Ionic 2 and I'm not going to waste my time trying to fix your SDK and so you're going to have one unhappy customer less. Best, Marcel

**Closed** 2016-12-01 18:20 UTC
