### ISSUE TITLE
iPhone 7 keyboard responsiveness

### ISSUE THREAD

**Issue by botbird** [smooch/smooch-js#515] opened 2017-03-31 04:06 UTC
The chat windows is over-extending once the keyboard on the iPhone 7.
This occurs on Safari and Chrome.
<img src="http://digitalninja.marketing/web-chat-iphone7-smooch-nourl.jpg" width="539px" height="960" style="max-width: 100%; height: auto">

**Comment by nathang21** [comment] 2017-03-31 04:14
This happens Everytime, very annoying

**Comment by lemieux** [comment] 2017-03-31 15:18
Hi @botbird, do you have a page I could inspect to understand what's going on? From the screenshot you shared, it seems like the page you are visiting is not fully responsive (seems to zoom in when focusing in the input). Usually using something like `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1”,  user-scalable=no>` in your page `head` helps with the problem.

**Comment by botbird** [comment] 2017-03-31 15:39
Hey @lemieux,
It is currently on napolinlaw.com.  The website is responsive and the chat window displays correctly up until the keyboard is extended on the iPhone 7.  I haven't been able to recreate the issue on a different device.

**Comment by lemieux** [comment] 2017-03-31 15:46
Which version of iOS are you running on that device?

I think we had some other reports about iOS troubles like this on Safari and Chrome and it was limited to a specific version/device. From past investigations, it seems that Chrome/Safari on iOS fails to update the actual viewport of the browser when zooming in an input and the page doesn't get any feedback at all about it (it still thinks it's the original height and width). 

We'll investigate.

**Comment by botbird** [comment] 2017-03-31 21:18
10.2.1 (14D27)

**Comment by bo25tbird** [comment] 2017-05-11 05:34
Was there any update on this?

**Comment by lemieux** [comment] 2017-05-18 17:39
Looking at napolinlaw.com, I can see that the viewport meta key is `<meta name="viewport" content="width=device-width, initial-scale=1.0">`. As I said above, you should try `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1”, user-scalable=no>` so the site wouldn't allow zoom on mobile. 

Based on preview error reports we received, I'm pretty positive the problem is that because the page is allowed to be zoomed in, Safari zooms in the input when it has focus. It's a browser behavior and we don't have much control over it.

I'll close this issue for now, but feel free to reopen it if you can't fix it with the `meta` change.

**Closed by lemieux** 2017-05-18 17:39 UTC

**Comment by nathang21** [comment] 2017-12-29 04:05
Is there any clever workarounds or auto-resizing logic that Smooch could have to prevent this issue?

Most of our users are iOS Safari, and even with the meta tag above, it doesn't help preventing unintentional zooming which gets smooch and the entire page into an unusual state.

**Comment by nathang21** [comment] 2017-12-30 03:13
Un-usable* state.
