### ISSUE TITLE
Chat bubble: missing shadow

### ISSUE THREAD

**Issue by skolarianer** [smooch/smooch-js#390] opened 2016-09-03 13:24 UTC
On Chrome the shadow of the chat bubble is not rendering. Source code seems to be Ok. Any idea why this happens?
![noshadow](https://cloud.githubusercontent.com/assets/6286711/18225043/dfd9c5ec-71e9-11e6-9a43-8f4ab38e7919.png)

On Firefox the bubble is missing at all
![nobubble](https://cloud.githubusercontent.com/assets/6286711/18225052/1fb013f6-71ea-11e6-9a9c-8bc66db79176.png)

**Comment by lemieux** [comment] 2016-09-06 14:06
Hi @skolarianer,

I found the problem for the missing dropshadow, but I can't repro the problem on Firefox. What version are you using? And could you set up a dummy page that reproduces the problem on your end that I can see?

**Comment by skolarianer** [comment] 2016-09-06 17:51
I see this behaviour at this page...
https://www.happyguests.de/login.html

Whereas at https://www.happyguests.de everything looks fine.

I'm using v3.4.0 via your CDN.

**Comment by lemieux** [comment] 2016-09-06 18:02
Okay, I was able to see the behavior on the login page, but I have no idea why it's happening on that page and not on the other. My first guess would be that something in the css on that page is interfering with the svg styling, but I can't pinpoint what it is. I'll add that to our bug tracker.

**Comment by lemieux** [comment] 2016-09-07 15:09
Hi @skolarianer,

I saw the problem on your login page, but it not happening on other pages. Also, I copied the markup and resources from your page to try to figure out the problem and it wasn't happening on the copied page.

I'm afraid I'll have to close this issue as this is very specific to that page. Something is definitely intefering with the svg and I can't figure out what it is. A workaround would be to upload an image for the button and it should show up correctly on all pages since it's not using a svg.

**Comment by skolarianer** [comment] 2016-09-07 18:14
@lemieux: Thanks for investigating.

I'm still trying to hunt down the differences between these two pages.
I'm pulling my hair off!
https://www.happyguests.de is just a pointer to https://www.happyguests.de/home.html. The source code is identical. The first link is showing the bubble whereas the second isn't.

**Comment by lemieux** [comment] 2016-11-07 16:23
I'm reopening this since #422 just confirmed it. A fix is in progress and will be released today.

**Comment by lemieux** [comment] 2016-11-07 16:44
Version 3.6.0 was just released and should contain the fix for this. Sorry it took that long to fix the problem, #422 provided the missing piece of the puzzle today!

**Comment by steinso** [comment] 2016-11-10 09:17
Looks like the fix breaks sites with # as part of the url. The chat bubble is missing in both Chrome and FF.

Example: http://example.com/#/home 
as the path to the filter becomes http://example.com/#/home/#dropShadow

Perhaps a combination of window.location.origin and window.location.pathname could work, however I have not investigated this.

**Comment by lemieux** [comment] 2016-11-10 15:05
Uh, you're right I'll push a fix today. I didn't think of that case!

**Comment by lemieux** [comment] 2016-11-10 20:55
Version 3.7.0 was just released with the fix.

**Closed by lemieux** 2016-11-10 20:55 UTC
